name: deepblock_env

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pytorch==1.12.1
  - cudatoolkit=11.3
  - mkl==2022.1.0
  # - cpuonly

  - numpy==1.24.3
  - scikit-learn==1.2.2
  - matplotlib==3.7.1
  - pandas==2.0.2
  - tpot==0.12.1
  - xgboost==1.7.4

  - botorch==0.8.5
  - gpytorch==1.12

  - rdkit==2023.03.1
  - biopython==1.81
  - openbabel==3.1.1

  - easydict==1.9
  - orjson==3.9.0
  - pyyaml==6.0
  - bidict==0.22.1

  - joblib==1.2.0
  - wandb==0.15.4
  - tqdm==4.65.0
  - halo==0.0.31
  - pexpect==4.8.0
  - psutil==5.9.5
  - requests==2.31.0

  - setuptools
  - pip
  
  - pip:
      - fair_esm==2.0.0
      - meeko==0.4.0
      - ormsgpack==1.2.6
