name: deepblock_env

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  ## Tested on Python 3.10 & PyTorch 1.11.0
  ## Tested on Python 3.7 & PyTorch 1.12.1
  - python=3.10
  - pytorch==1.12.1
  ## GPU required or CPU only?
  - cudatoolkit=11.3
  # - cpuonly

  - numpy
  - scikit-learn
  - matplotlib
  - pandas
  - tpot
  - xgboost

  - rdkit
  - biopython
  - openbabel

  - easydict
  - orjson
  - pyyaml
  - bidict

  - joblib
  - wandb
  - tqdm
  - halo
  - pexpect
  - psutil
  - requests

  - setuptools
  - pip
  - pip:
      - fair_esm==2.0.0
      - meeko
      - ormsgpack
