warm_batch_size: 32
batch_size: 64
valid_batch_size: 256
num_workers: 8

# beta_vae:
#     mode: fix
#     value: 0.1

max_epochs: 200
optim_lr: 1.0e-3

optim_lr_scheduler:
    mode: MultiStepLR
    value:
        milestones: [20, 40, 120]
        gamma: 0.1

beta_vae:
    mode: annealing
    value:
        cycle: 0
        min_point: 0
        max_point: 200
        min_beta: 1.0e-5
        max_beta: 1
        